services:
  react-client:
    container_name: Frontend
    build:
      context: ./Clients/web
    ports:
      - "5173:80"
    depends_on:
      - spring-server
    networks:
      - app-network

  spring-server:
    container_name: Backend
    build:
      context: ./Server
    ports:
      - "8080:8080"
    depends_on:
      - ai-service
      - mongo
    networks:
      - app-network

  ai-service:
    container_name: AI-service
    build:
      context: ./Server/services/ai-service
    ports:
      - "5000:5000"
    networks:
      - app-network

  mongo:
    container_name: MongoDB
    image: mongo:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file: ./Database/mongo/mongo.env
    volumes:
      - mongo_data:/data/db
      - ./Database/mongo/logs:/logs
      - ./Database/mongo/config:/etc/mongo/
    networks:
      - app-network

  ollama:
    container_name: Ollama
    image: ollama/ollama:latest
    pull_policy: if_not_present
    tty: true
    # mem_limit: "8G"
    # restart: unless-stopped
    ports:
      - "7869:11434"
    environment:
      OLLAMA_KEEP_ALIVE: 24h
      OLLAMA_HOST: 0.0.0.0
    deploy:
      resources:
        limits:
          memory: 8G
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: all
        #       capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./Database/mongo/data
      o: bind

  ollama_data:
    driver: local
    driver_opts:
      type: none
      device: ./Ollama/data
      o: bind

networks:
  app-network:
    driver: bridge
