package com.augmentedcooking.Enums.Http;

public enum ErrorCodes {
    /**
     * Informational responses
     */
    CONTINUE("CONTINUE"),
    SWITCHING_PROTOCOLS("SWITCHING_PROTOCOLS"),
    PROCESSING_DEPRECATED("PROCESSING_DEPRECATED"),
    EARLY_HINTS("EARLY_HINTS"),

    /**
     * Successful responses
     */
    OK("OK"),
    CREATED("CREATED"),
    ACCEPTED("ACCEPTED"),
    NONAUTHORITATIVE_INFORMATION("NONAUTHORITATIVE_INFORMATION"),
    NO_CONTENT("NO_CONTENT"),
    RESET_CONTENT("RESET_CONTENT"),
    PARTIAL_CONTENT("PARTIAL_CONTENT"),
    MULTISTATUS("MULTISTATUS"),
    ALREADY_REPORTED("ALREADY_REPORTED"),
    IM_USED("IM_USED"),

    /**
     * Redirection messages
     */
    MULTIPLE_CHOICES("MULTIPLE_CHOICES"),
    MOVED_PERMANENTLY("MOVED_PERMANENTLY"),
    FOUND("FOUND"),
    SEE_OTHER("SEE_OTHER"),
    NOT_MODIFIED("NOT_MODIFIED"),
    USE_PROXY_DEPRECATED("USE_PROXY_DEPRECATED"),
    UNUSED("UNUSED"),
    TEMPORARY_REDIRECT("TEMPORARY_REDIRECT"),
    PERMANENT_REDIRECT("PERMANENT_REDIRECT"),

    /**
     * Client error responses
     */
    BAD_REQUEST("BAD_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    PAYMENT_REQUIRED("PAYMENT_REQUIRED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    NOT_ACCEPTABLE("NOT_ACCEPTABLE"),
    PROXY_AUTHENTICATION_REQUIRED("PROXY_AUTHENTICATION_REQUIRED"),
    REQUEST_TIMEOUT("REQUEST_TIMEOUT"),
    CONFLICT("CONFLICT"),
    GONE("GONE"),
    LENGTH_REQUIRED("LENGTH_REQUIRED"),
    PRECONDITION_FAILED("PRECONDITION_FAILED"),
    CONTENT_TOO_LARGE("CONTENT_TOO_LARGE"),
    URI_TOO_LONG("URI_TOO_LONG"),
    UNSUPPORTED_MEDIA_TYPE("UNSUPPORTED_MEDIA_TYPE"),
    RANGE_NOT_SATISFIABLE("RANGE_NOT_SATISFIABLE"),
    EXPECTATION_FAILED("EXPECTATION_FAILED"),
    IM_A_TEAPOT("IM_A_TEAPOT"),
    MISDIRECTED_REQUEST("MISDIRECTED_REQUEST"),
    UNPROCESSABLE_CONTENT("UNPROCESSABLE_CONTENT"),
    LOCKED("LOCKED"),
    FAILED_DEPENDENCY("FAILED_DEPENDENCY"),
    TOO_EARLY_EXPERIMENTAL("TOO_EARLY_EXPERIMENTAL"),
    UPGRADE_REQUIRED("UPGRADE_REQUIRED"),
    PRECONDITION_REQUIRED("PRECONDITION_REQUIRED"),
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS"),
    REQUEST_HEADER_FIELDS_TOO_LARGE("REQUEST_HEADER_FIELDS_TOO_LARGE"),
    UNAVAILABLE_FOR_LEGAL_REASONS("UNAVAILABLE_FOR_LEGAL_REASONS"),

    /**
     * Server error responses
     */
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    NOT_IMPLEMENTED("NOT_IMPLEMENTED"),
    BAD_GATEWAY("BAD_GATEWAY"),
    SERVICE_UNAVAILABLE("SERVICE_UNAVAILABLE"),
    GATEWAY_TIMEOUT("GATEWAY_TIMEOUT"),
    HTTP_VERSION_NOT_SUPPORTED("HTTP_VERSION_NOT_SUPPORTED"),
    VARIANT_ALSO_NEGOTIATES("VARIANT_ALSO_NEGOTIATES"),
    INSUFFICIENT_STORAGE("INSUFFICIENT_STORAGE"),
    LOOP_DETECTED("LOOP_DETECTED"),
    NOT_EXTENDED("NOT_EXTENDED"),
    NETWORK_AUTHENTICATION_REQUIRED("NETWORK_AUTHENTICATION_REQUIRED");

    private final String errorCode;

    ErrorCodes(String errorCode) {
        this.errorCode = errorCode;
    }

    public String value() {
        return errorCode;
    }
}
